import{test} from "@playwright/test"

test("verify create lead functionality",async({page})=>
{   
    await page.goto("https://login.salesforce.com/")
    await page.getByRole("textbox",{name:"Username"}).fill("devisairam.5725a90629db@agentforce.com")
    await page.getByRole("button",{name:"Log In"}).click()
    await page.locator('#password').fill("Hrishi12#")
    await page.getByRole("button",{name:"Log In"}).click()
    await page.getByTitle("App Launcher").click()
    await page.locator('//p[text()="Sales"]').click()
    await page.locator('//span[text()="Leads"]').first().click()
    await page.locator('//a[@title="New"]').click()
    await page.locator('//button[@name="salutation"]').click()
    await page.locator('//span[text()="Ms."]').click()
    await page.locator("//input[@name='lastName']").fill("Devi")
    await page.locator("//input[@name='Company']").fill("CTS")
    await page.locator('//button[text()="Save"]').nth(1).click()
    await page.waitForTimeout(2000)
})

test("Edit Lead functionality", async({page})=>
{
    await page.goto("https://login.salesforce.com/")
    await page.getByRole("textbox",{name:"Username"}).fill("devisairam.5725a90629db@agentforce.com")
    await page.getByRole("button",{name:"Log In"}).click()
    await page.locator('#password').fill("Hrishi12#")
    await page.getByRole("button",{name:"Log In"}).click()
    await page.getByTitle("App Launcher").click()
    await page.locator('//p[text()="Sales"]').click()
    await page.locator('//span[text()="Leads"]').first().click()
    await page.waitForTimeout(2000)  
    await page.locator('//button[@title="Edit List"]').click()
    await page.locator('//input[@name="Lead-search-input"]').fill("Devi")
    await page.locator('//td[@class="slds-cell-edit"]').first().click()
    await page.getByRole('button', {name:"Edit Title"}).first().click()
    await page.locator('//input[@name="Title"]').fill("Mrs.")
    await page.locator('//input[@name="Title"]').press('Enter')
    await page.locator('//td[@class="slds-cell-edit"]').nth(1).click()
    await page.getByRole('button', {name:"Edit Company"}).nth(0).click()    
    await page.locator('//input[@name="Company"]').fill("TCS")
    await page.locator('//input[@name="Company"]').press('Enter')
    await page.getByRole("button",{name:"Save"}).click()
    await page.waitForTimeout(2000)    
})

test("Create Individuals",async({page})=>
{
    await page.goto("https://login.salesforce.com/")
    await page.getByRole("textbox",{name:"Username"}).fill("devisairam.5725a90629db@agentforce.com")
    await page.getByRole("button",{name:"Log In"}).click()
    await page.locator('#password').fill("Hrishi12#")
    await page.getByRole("button",{name:"Log In"}).click()
    await page.getByTitle("App Launcher").click()
    await page.locator('//button[@aria-label="View All Applications"]').click()
    await page.getByPlaceholder("Search apps or items...").fill("Individuals")
    await page.getByPlaceholder("Search apps or items...").press('Enter')
    await page.getByRole('link',{name:"Individuals"}).click()
    await page.getByRole('button',{name:"New"}).click()
    await page.getByRole('textbox',{name:"Last Name"}).fill("Sairam")
    await page.locator('//button[@title="Save"]').last().click()
    await page.waitForTimeout(2000)
})

test("Edit Individuals",async({page})=>
{
   await page.goto("https://login.salesforce.com/")
    await page.getByRole("textbox",{name:"Username"}).fill("devisairam.5725a90629db@agentforce.com")
    await page.getByRole("button",{name:"Log In"}).click()
    await page.locator('#password').fill("Hrishi12#")
    await page.getByRole("button",{name:"Log In"}).click()
    await page.getByTitle("App Launcher").click()
    await page.locator('//button[@aria-label="View All Applications"]').click()
    await page.getByPlaceholder("Search apps or items...").fill("Individuals")
    await page.getByPlaceholder("Search apps or items...").press('Enter')
    await page.getByRole('link',{name:"Individuals"}).click()
    await page.locator('[name="Individual-search-input"]').fill("Sairam")
    await page.locator('[name="Individual-search-input"]').press('Enter')
    await page.locator('//a[@title="Sairam"]').click()
    await page.locator('//a[@title="Edit"]').last().click()
    await page.getByRole('button',{name:"Salutation --None--"}).click()
    await page.locator('//li/a[text()="Mr."]').click()
    await page.getByPlaceholder("First Name").fill("Devi")
    await page.getByTitle("Save").last().click()
    await page.waitForTimeout(2000) 
})